[[redirects]]
    from = "https://bloemstraatgarden.netlify.app/*"
    to = "https://www.bloemstraatgarden.nl/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://bloemstraatgarden.netlify.app"
    to = "https://www.bloemstraatgarden.nl"
    status = 301
    force = true